Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asistenteventas.Data;
using asistenteventas.Models;
using Microsoft.AspNetCore.Authorization;

namespace asistenteventas.Controllers
{
    
    public class ClientsController : Controller
    {
        private readonly ASISTENTE_DE_VENTASContext _context;

        public ClientsController(ASISTENTE_DE_VENTASContext context)
        {
            _context = context;
        }

        // GET: Clients


        // GET: Clients/Details/5
        [Authorize(Roles = "1,2")]
        public async Task<IActionResult> Details(decimal? id)
        {
            if (id == null || _context.Clients == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.CodCli == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        [Authorize(Roles = "1,2")]
        public IActionResult CreateCliente()
        {
           
                return View();
           

        }

        // POST: Clients/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "1,2")]
        public async Task<IActionResult> CreateCliente([Bind("CodCli,MailCli,PriNomCli,NroDocCli,PriApeCli,SegApeCli")] Client client)
        {
            try { 
            if (ModelState.IsValid)
            {
                if (client == null)
                {
                    ViewBag.mje = "No se ha creado el cliente con éxito";
                    return View();
                }

                _context.Add(client);
                await _context.SaveChangesAsync();

                // Establece un mensaje de éxito en ViewBag
                ViewBag.mje = "Cliente creado con éxito";

                    // Devuelve la vista "Create" con el mensaje de éxito
                    return RedirectToAction("Details", new { id = client.CodCli });
                } 
                
                return View(client);
            }catch (Exception ex)
            {
                ViewBag.mje = "error en crear cliente, favor  inetente nuevamente";
                return View(client);
            }

          
        }




        public ActionResult Encuesta()
        {
            ViewBag.mje = "";
            return View();
        }
        [HttpPost]
        public ActionResult Encuesta(string cedula, string calificacion, string comentario)
        {
            try
            {
                var facloc = _context.Faclocs.Where(f => f.CodCli == decimal.Parse(cedula)).OrderByDescending(f => f.FecFacLoc).FirstOrDefault();
                var facloc1 = _context.Facloc1s.Where(f1 => f1.Facloc == facloc).FirstOrDefault();
                if (facloc1 == null)
                {
                    ViewBag.mje = "no se pudo hacer la encuesta correctamente";
                    return View();
                }
                //creo un nuevo regustro de  la tabla datoscompras
                DatosCompras dt = new DatosCompras(decimal.Parse(cedula), facloc1.CodArt, int.Parse(calificacion), comentario);

                _context.Add(dt);
                _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                ViewBag.mje = ex.Message;
                return View();
            }
            ViewBag.mje = "Encuesta Completa muchas gracias !!";
            return View();
        }



    }
}

Controllers/UsuariosController.cs
using asistenteventas.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;

namespace asistenteventas.Controllers
{
   
    public class UsuariosController : Controller
    {
        private readonly ASISTENTE_DE_VENTASContext _context;
        public UsuariosController(ASISTENTE_DE_VENTASContext context)
        {
            _context = context;
        }
        public IActionResult Login()
        {

            if (User.IsInRole("1"))
            {
                return RedirectToAction("Index", "Administradors");
            }
            else if (User.IsInRole("2"))
            {
                return RedirectToAction("Index", "Vendedors");
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Login(string n, string c)
        {

            if (User.HasClaim("Logged", "true"))
            {
                ViewBag.mje = "Ya hay una sesión activa para este usuario.";
                if (User.IsInRole("1"))
                {
                    return RedirectToAction("Index", "Administradors");
                }
                else if (User.IsInRole("2"))
                {
                    return RedirectToAction("Index", "Vendedors");
                }
            }
            try
            {
                var usu = _context.Usuarios.FirstOrDefault(
                u => u.nombre == n && u.passsword == c);

                if (usu == null)
                {
                    ViewBag.mje = "login incorrecto";
                    return View();
                }
                else
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, usu.nombre),
                        new Claim("password", usu.passsword),
                         new Claim("Logged", "true")
                    };
                    claims.Add(new Claim(ClaimTypes.Role, usu.rol.ToString()));
                    var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                    if (usu.rol == 1)
                    {
                        HttpContext.Session.SetString("Admi", usu.nombre);
                        return RedirectToAction("Index", "Administradors");
                    }
                    if (usu.rol == 2)
                    {
                        HttpContext.Session.SetString("Vend", usu.nombre);
                        return RedirectToAction("Index", "Vendedors");
                    }
                    return View();
                }

            }
            catch (Exception ex)
            {
                ViewBag.mje = "login incorrecto";
                return View();
            }
        }
        // GET: Vendedors
        [Authorize(Roles = "1,2")]
        public IActionResult Logout()
        {

            return View();

        }


        [HttpPost]
        [Authorize(Roles = "1,2")]
        public async Task<IActionResult> Logout(string n)
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction("Login");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - asistenteventas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/asistenteventas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
               
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">




                        @if (User.IsInRole("2"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendedors" asp-action="Index">Recomendar a cliente</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendedors" asp-action="BuscarporTexto">Buscar Por Texto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendedors" asp-action="Busqueda">Buscar Por Foto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendedors" asp-action="BusquedaSubir">Buscar Subiendo imagen</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="CreateCliente">Nuevo Cliente</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Salir</a>
                            </li>
                        }
                        @if (User.IsInRole("1"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clients" asp-action="CreateCliente">Nuevo Cliente</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administradors" asp-action="Index">Gestion Vendedores</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendedors" asp-action="BuscarporTexto">Buscar Por Texto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendedors" asp-action="Busqueda">Buscar Por Foto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendedors" asp-action="BusquedaSubir">Buscar Subiendo imagen</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Logout">Salir</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>