Models/Stock.cs
using System;
using System.Collections.Generic;

namespace asistenteventas.Models
{
    public partial class Stock
    {
#pragma warning disable CS8618 // El elemento propiedad "Imagen" que no acepta valores NULL debe contener un valor distinto de NULL al salir del constructor. Considere la posibilidad de declarar el elemento propiedad como que admite un valor NULL.
        public Stock()
#pragma warning restore CS8618 // El elemento propiedad "Imagen" que no acepta valores NULL debe contener un valor distinto de NULL al salir del constructor. Considere la posibilidad de declarar el elemento propiedad como que admite un valor NULL.
        {
            Facloc1s = new HashSet<Facloc1>();
        }

        public string CodArt { get; set; } = null!;
        public string? DesArt { get; set; }
        public string? DesDetArt { get; set; }
        public string? CodMod { get; set; }
        public string? CodColPrv { get; set; }
        public string? CodTalPrv { get; set; }
        public string? CodArtAlt { get; set; }
        public int SalWebArt { get; set; }

        public virtual Modelo? CodModNavigation { get; set; }
        public virtual ICollection<Facloc1> Facloc1s { get; set; }

        public override bool Equals(object? obj)
        {
            return base.Equals(obj);
        }

        public override int GetHashCode()
        {
            return base.GetHashCode();
        }
    }
}

Controllers/AdministradorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using asistenteventas.Data;
using asistenteventas.Models;
using MimeKit;
using Microsoft.AspNetCore.Authorization;

namespace asistenteventas.Controllers
{
    [Authorize(Roles = "1,1")]
    public class AdministradorsController : Controller
    {
        private readonly ASISTENTE_DE_VENTASContext _context;

        public AdministradorsController(ASISTENTE_DE_VENTASContext context)
        {
            _context = context;
        }

        // GET: Administradors1
        [Authorize(Roles = "1,1")]
        public async Task<IActionResult> Index()
        {
            var aSISTENTE_DE_VENTASContext = _context.Usuarios.Where(u=>u.rol ==2);
            return View(await aSISTENTE_DE_VENTASContext.ToListAsync());
        }
        [Authorize(Roles = "1,1")]
        public IActionResult EnviarCorreo()
        {
            // Obtener la fecha y hora actuales
            DateTime ayer = DateTime.Today;

            //Consultar si hay nuevas compras realizadas a partir de las 00 horas del día de ayer
            var nuevascompras = _context.Faclocs.Where(p => p.FecFacLoc > ayer).ToList();
            if (nuevascompras.Count > 0)
            {


                // Enviar un correo electrónico a cada  usuario con link a la encuesta
                foreach (var compra in nuevascompras)
                {
                    var usu = _context.Clients.Where(c => c.CodCli == compra.CodCli).SingleOrDefault();
                    //creo el mensaje con todas sus partes 
                    var mensaje = new MimeMessage();
                    mensaje.From.Add(new MailboxAddress("Administrador", "edwardjunior49@gmail.com"));
                    mensaje.To.Add(new MailboxAddress(usu.PriNomCli, usu.MailCli));
                    mensaje.Subject = "Encuesta sobre su compra";

                    var bodyBuilder = new BodyBuilder();
                    bodyBuilder.HtmlBody = "<h1>Encuesta sobre su compra</h1><p>Por favor, complete la siguiente encuesta:</p><a href=\"http://localhost:5214/Clients/Encuesta\">Ir a la encuesta</a>";
                    mensaje.Body = bodyBuilder.ToMessageBody();
                    //me conecto co autenticacion 
                    using (var client = new MailKit.Net.Smtp.SmtpClient())
                    {
                        client.Connect("smtp.gmail.com", 587, false);
                        client.Authenticate("edwardjunior49@gmail.com", "bxdsvybobxgxzxli");
                        client.Send(mensaje);
                        //me desconecto
                        client.Disconnect(true);
                    }
                }

            }
            ViewBag.men = "Correos enviados ";
            var ven = _context.Usuarios.Where(u => u.rol == 2);
            return View("Index", ven);
        }

    }
}

Controllers/VendedorsController.cs
using asistenteventas.Data;
using asistenteventas.Models;
using Asistenteventas;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text;
using System.Drawing;
using System.Drawing.Imaging;
using AForge.Imaging.Filters;
using Microsoft.AspNetCore.Authorization;


namespace asistenteventas.Controllers
{
   
    public class VendedorsController : Controller
    {
        private readonly ASISTENTE_DE_VENTASContext _context;

#pragma warning disable CS8618 // El elemento campo "_stocks" que no acepta valores NULL debe contener un valor distinto de NULL al salir del constructor. Considere la posibilidad de declarar el elemento campo como que admite un valor NULL.
        public VendedorsController(ASISTENTE_DE_VENTASContext context)
#pragma warning restore CS8618 // El elemento campo "_stocks" que no acepta valores NULL debe contener un valor distinto de NULL al salir del constructor. Considere la posibilidad de declarar el elemento campo como que admite un valor NULL.
        {
            _context = context;
        }

        private IEnumerable<Stock> _stocks;
        //busqueda
        [Authorize(Roles = "1,2")]
        public ActionResult Busqueda()
        {
             
                return View();

        }
        [Authorize(Roles = "1,2")]
        [HttpPost]
        public ActionResult Busqueda(string imagen)
        {
            _stocks = null;
            try
            {
                if (string.IsNullOrEmpty(imagen))
                {
                    ViewBag.mje = "No se ha proporcionado ninguna imagen.";
                    return View();
                }

                byte[] bytes ;
                try
                {
                    bytes = Convert.FromBase64String(imagen);
                }
                catch (Exception ex)
                {
                    ViewBag.mje = "El formato de la imagen proporcionada no es correcto.";
                    return View();
                }
              
                string[] busqueda = RealizarBusqueda(bytes);

                IEnumerable<StockAmpliado> stocks = ObtenerStocks(busqueda);

                if (stocks != null && stocks.Any())
                {
                    ViewBag.mje = "Modelos encontrados de: " + busqueda;
                    return View("Stock", stocks);
                }
                else
                {
                    ViewBag.mje = "No se encontraron modelos con esa foto.";
                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.mje = "Error al buscar por foto: " + ex.Message;
                return View();
            }
        }
        [Authorize(Roles = "1,2")]
        public ActionResult BusquedaSubir()
        {
            
                return View();

        }
        [Authorize(Roles = "1,2")]
        [HttpPost]
        public ActionResult BusquedaSubir(IFormFile imagenFile)
        {
            _stocks = null;
            try
            {
                if (imagenFile == null || imagenFile.Length == 0)
                {
                    ViewBag.mje = "No se ha proporcionado ninguna imagen.";
                    return View();
                }

                using (var memoryStream = new MemoryStream())
                {
                    imagenFile.CopyTo(memoryStream);
                    byte[] bytes = memoryStream.ToArray();

                    string[] busqueda = RealizarBusqueda(bytes);

                    IEnumerable<StockAmpliado> stocks = ObtenerStocks(busqueda);

                    if (stocks != null && stocks.Any())
                    {
                        ViewBag.mje = "Modelos encontrados de: " + busqueda;
                        return View("Stock", stocks);
                    }
                    else
                    {
                        ViewBag.mje = "No se encontraron modelos con esa foto.";
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.mje = "Error al buscar por foto: " + ex.Message;
                return View();
            }
        }
        [Authorize(Roles = "1,2")]
        private string[] RealizarBusqueda(byte[] imagenBytes)
        {
            string tipoPrenda = CargarTipoPrenda(imagenBytes);
            string color = DetectarColor(imagenBytes);
            string textura = CargarTextura(imagenBytes);
            string suma = $"{tipoPrenda}_{color}_{textura}";
            string[] ret = suma.Split('_', StringSplitOptions.RemoveEmptyEntries);
            return ret;
        }

        [Authorize(Roles = "1,2")]

        private IEnumerable<StockAmpliado> ObtenerStocks(string[] busqueda)
        {
            IEnumerable<StockAmpliado> stocks = _context.Stocks
                .Select(s => new StockAmpliado
                {
                    Stock = s,
                    Color = _context.CodigosColor
                        .Where(cc => cc.CodCol == s.CodColPrv)
                        .Select(cc => cc.Nombre)
                        .FirstOrDefault() ?? ""
                })
                .AsEnumerable();

            stocks = FiltrarYOrdenarStocks(stocks, busqueda);
            return AsignarImagenesAStocks(stocks);
        }
		private IEnumerable<StockAmpliado> AsignarImagenesAStocks(IEnumerable<StockAmpliado> stocks)
		{
			var stocksConImagenes = stocks.Select(stock =>
			{
				var imagen = ObtenerImagen(stock.Stock.CodArt);
				stock.Imagen = imagen;
				return stock;
			});

			return stocksConImagenes;
		}

		private byte[] ObtenerImagen(string codArt)
		{
			var imagen = _context.Images
				.Where(i => i.CodArt == codArt)
				.Select(i => i.Imagen)
				.FirstOrDefault();

			return imagen;
		}


		[Authorize(Roles = "1,2")]
        private string CargarTipoPrenda(byte[] bytes)
        {
            ClasificarImgTipoPrenda.ModelInput sampleData = new ClasificarImgTipoPrenda.ModelInput()
            {
                ImageSource = bytes,
            };

            return ClasificarImgTipoPrenda.Predict(sampleData).PredictedLabel;
        }

        [Authorize(Roles = "1,2")]
        private string CargarTextura(byte[] bytes)
        {
            ClasificarImgTextura.ModelInput sampleData2 = new ClasificarImgTextura.ModelInput()
            {
                ImageSource = bytes,
            };

            return ClasificarImgTextura.Predict(sampleData2).PredictedLabel;
        }

        [Authorize(Roles = "1,2")]
        private IEnumerable<StockAmpliado> FiltrarYOrdenarStocks(IEnumerable<StockAmpliado> stocks, string[] palabras)
        {
            return stocks
                .Where(m => CalcularPuntaje(m, palabras) > 0)
                .OrderByDescending(m => CalcularPuntaje(m, palabras))
                .Take(12)
                .ToList();
        }

        [Authorize(Roles = "1,2")]
        public ActionResult Stock()
        {
            
                if (_stocks != null && _stocks.Any())
                {
                    ViewBag.mje = "Modelos encontrados:";
                    return View(_stocks);
                }
                else
                {
                    ViewBag.mje = "No se encontraron modelos.";
                    return View();
                }
           

        }

        private string DetectarColor(byte[] archivo)
        {
            if (archivo == null || archivo.Length == 0)
            {
                return "No se seleccionó ninguna imagen.";
            }

            try
            {
                using (MemoryStream stream = new MemoryStream(archivo))
                using (Bitmap imagenOriginal = new Bitmap(stream))
                {
                    // Redimensionar la imagen a un tamaño más pequeño (por ejemplo, 100x100 píxeles)
                    int nuevoAncho = 100;
                    int nuevoAlto = 100;
                    Bitmap imagenRedimensionada = RedimensionarImagen(imagenOriginal, nuevoAncho, nuevoAlto);

                    ResizeBicubic filter = new ResizeBicubic(100, 100);

                    Color color = ObtenerColorPredominante(imagenOriginal, 30);
                    string nombreColor = GetNombreColor(color);

                    return nombreColor;
                }
            }
            catch (Exception ex)
            {
                return "Error al procesar la imagen: " + ex.Message;
            }
        }
        private Bitmap RedimensionarImagen(Bitmap imagenOriginal, int nuevoAncho, int nuevoAlto)
        {
            Bitmap imagenRedimensionada = new Bitmap(nuevoAncho, nuevoAlto);

            using (Graphics graficos = Graphics.FromImage(imagenRedimensionada))
            {
                // Configurar opciones de calidad de interpolación
                graficos.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic;
                graficos.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.HighQuality;
                graficos.PixelOffsetMode = System.Drawing.Drawing2D.PixelOffsetMode.HighQuality;
                graficos.CompositingQuality = System.Drawing.Drawing2D.CompositingQuality.HighQuality;

                // Redimensionar la imagen original al nuevo tamaño
                graficos.DrawImage(imagenOriginal, new Rectangle(0, 0, nuevoAncho, nuevoAlto));
            }

            return imagenRedimensionada;
        }

        private Color ObtenerColorPredominante(Bitmap imagen, int radio)
        {
            int centroX = imagen.Width / 2;
            int centroY = imagen.Height / 2;

            int startX = Math.Max(0, centroX - radio);
            int startY = Math.Max(0, centroY - radio);
            int endX = Math.Min(imagen.Width - 1, centroX + radio);
            int endY = Math.Min(imagen.Height - 1, centroY + radio);

            Dictionary<Color, int> colorCounts = new Dictionary<Color, int>();

Views/Vendedors/Busqueda - Copia.cshtml
@{
    ViewData["Title"] = "Busqueda";
}

 <div >
    <form asp-action="Busqueda" id="form" enctype="multipart/form-data">
		<div class="form-group">
		<input type="text" name="imagen" id="imagen" readonly />
		</div>
			<h1>Selecciona un dispositivo</h1>
			<div>
				<select name="listaDeDispositivos" id="listaDeDispositivos"></select>
			<div class="form-group">
                <input type="submit" id="boton" value="Tomar foto" class="btn btn-primary" />
			</div>
				<p id="estado"></p>
			</div>
        <br>
		<div>
        
        </div>
			<video muted="muted" id="video" class="im"></video>
			<canvas id="canvas" style="display: none;"></canvas>
     </form>
</div>

@section  Scripts {
<script >
		

	function tieneSoporteUserMedia() {
		return !!(navigator.getUserMedia || (navigator.mozGetUserMedia || navigator.mediaDevices.getUserMedia) || navigator.webkitGetUserMedia || navigator.msGetUserMedia)
	}
	function _getUserMedia() {
		return (navigator.getUserMedia || (navigator.mozGetUserMedia || navigator.mediaDevices.getUserMedia) || navigator.webkitGetUserMedia || navigator.msGetUserMedia).apply(navigator, arguments);
	}
	 let form = document.querySelector('#form');
		
	// Declaramos elementos del DOM
	const $video = document.querySelector("#video"),
		$canvas = document.querySelector("#canvas"),
		$boton = document.querySelector("#boton"),
		$estado = document.querySelector("#estado"),
		$listaDeDispositivos = document.querySelector("#listaDeDispositivos");
 
	// La función que es llamada después de que ya se dieron los permisos
	// Lo que hace es llenar el select con los dispositivos obtenidos
	const llenarSelectConDispositivosDisponibles = () => {
 
		navigator
			.mediaDevices
			.enumerateDevices()
			.then(function (dispositivos) {
				const dispositivosDeVideo = [];
				dispositivos.forEach(function (dispositivo) {
					const tipo = dispositivo.kind;
					if (tipo === "videoinput") {
						dispositivosDeVideo.push(dispositivo);
					}
				});
 
				// Vemos si encontramos algún dispositivo, y en caso de que si, entonces llamamos a la función
				if (dispositivosDeVideo.length > 0) {
					// Llenar el select
					dispositivosDeVideo.forEach(dispositivo => {
						const option = document.createElement('option');
						option.value = dispositivo.deviceId;
						option.text = dispositivo.label;
						$listaDeDispositivos.appendChild(option);
						//console.log("$listaDeDispositivos => ", $listaDeDispositivos)
					});
				}
			});
	}
 
	(function () {
		// Comenzamos viendo si tiene soporte, si no, nos detenemos
		if (!tieneSoporteUserMedia()) {
			alert("Lo siento. Tu navegador no soporta esta característica");
			$estado.innerHTML = "Parece que tu navegador no soporta esta característica. Intenta actualizarlo.";
			return;
		}
		//Aquí guardaremos el stream globalmente
		let stream;
 
 
		// Comenzamos pidiendo los dispositivos
		navigator
			.mediaDevices
			.enumerateDevices()
			.then(function (dispositivos) {
				// Vamos a filtrarlos y guardar aquí los de vídeo
				const dispositivosDeVideo = [];
 
				// Recorrer y filtrar
				dispositivos.forEach(function (dispositivo) {
					const tipo = dispositivo.kind;
					if (tipo === "videoinput") {
						dispositivosDeVideo.push(dispositivo);
					}
				});
 
				// Vemos si encontramos algún dispositivo, y en caso de que si, entonces llamamos a la función
				// y le pasamos el id de dispositivo
				if (dispositivosDeVideo.length > 0) {
					// Mostrar stream con el ID del primer dispositivo, luego el usuario puede cambiar
					mostrarStream(dispositivosDeVideo[0].deviceId);
				}
			});
 
		const mostrarStream = idDeDispositivo => {
			_getUserMedia(
				{
					video: {
						// Justo aquí indicamos cuál dispositivo usar
						deviceId: idDeDispositivo,
					}
				},
				function (streamObtenido) {
					// Aquí ya tenemos permisos, ahora sí llenamos el select,
					// pues si no, no nos daría el nombre de los dispositivos
					llenarSelectConDispositivosDisponibles();
 
					// Escuchar cuando seleccionen otra opción y entonces llamar a esta función
					$listaDeDispositivos.onchange = () => {
						// Detener el stream
						if (stream) {
							stream.getTracks().forEach(function (track) {
								track.stop();
							});
						}
						// Mostrar el nuevo stream con el dispositivo seleccionado
						mostrarStream($listaDeDispositivos.value);
					}
 
					// Simple asignación
					stream = streamObtenido;
 
					// Mandamos el stream de la cámara al elemento de vídeo
					$video.srcObject = stream;
					$video.play();
 
					//Escuchar el click del botón para tomar la foto
					$boton.addEventListener("click", function () {
						event.preventDefault();
 
						//Pausar reproducción
						$video.pause();
 
						//Obtener contexto del canvas y dibujar sobre él
						let contexto = $canvas.getContext("2d");
						$canvas.width = $video.videoWidth;
						$canvas.height = $video.videoHeight;
						contexto.drawImage($video, 0, 0, $canvas.width, $canvas.height);
 
						const foto = $canvas.toDataURL().split(',')[1];; //Esta es la foto, en base 64
						
							
						$estado.innerHTML = "Enviando foto. Por favor, espera...";
					
						/*var uri = '@Url.Action("Busqueda", "Vendedors")';
						//enviar imagen al controlador
						$.ajax({
							url: uri,
							type: 'POST',
										data: { imagen: foto }
						
						});*/
							document.querySelector('#imagen').value = foto;
						form.submit();

						
					});
				}, function (error) {
					console.log("Permiso denegado o error: ", error);
					$estado.innerHTML = "No se puede acceder a la cámara, o no diste permiso.";
				});
		}
	})();
</script>
 }

Views/Vendedors/Busqueda.cshtml
@{
    ViewData["Title"] = "Búsqueda por Foto";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>

    <!-- Vincula el archivo CSS externo -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css">
    <style>
        .container {
            max-width: 100%;
            overflow-x: auto;
        }


        #video {
            width: 100%;
            height: auto;
            object-fit: cover;
        }


        .fixed-buttons {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: white;
            z-index: 1;
            padding: 10px;
            box-shadow: 0px -5px 10px rgba(0, 0, 0, 0.1);
            justify-content: center;
            align-items: center;
            text-align: center;
        }
    </style>
  
</head>
<body>
    <div class="container">
        <h1>@ViewData["Title"]</h1>
        <form asp-action="Busqueda" id="form" enctype="multipart/form-data">
            <div class="form-group">
                <input type="hidden" name="imagen" id="imagen" readonly />
            </div>
            <div class="form-group">
                <label for="listaDeDispositivos">Selecciona un dispositivo</label>
                <select class="form-control" name="listaDeDispositivos" id="listaDeDispositivos"></select>
            </div>
            <div class="form-group">
                <input type="submit" id="boton" value="Tomar foto" class="btn btn-primary fixed-buttons" />
            </div>
            <p id="estado"></p>
            <video muted="muted" id="video" class="img"></video>
            <canvas id="canvas" style="display: none;"></canvas>
        </form>
    </div>


</body>
</html>

<script>


    function tieneSoporteUserMedia() {
        return !!(navigator.getUserMedia || (navigator.mozGetUserMedia || navigator.mediaDevices.getUserMedia) || navigator.webkitGetUserMedia || navigator.msGetUserMedia)
    }
    function _getUserMedia() {
        return (navigator.getUserMedia || (navigator.mozGetUserMedia || navigator.mediaDevices.getUserMedia) || navigator.webkitGetUserMedia || navigator.msGetUserMedia).apply(navigator, arguments);
    }
    let form = document.querySelector('#form');

    // Declaramos elementos del DOM
    const $video = document.querySelector("#video"),
        $canvas = document.querySelector("#canvas"),
        $boton = document.querySelector("#boton"),
        $estado = document.querySelector("#estado"),
        $listaDeDispositivos = document.querySelector("#listaDeDispositivos");

    // La función que es llamada después de que ya se dieron los permisos
    // Lo que hace es llenar el select con los dispositivos obtenidos
    const llenarSelectConDispositivosDisponibles = () => {

        navigator
            .mediaDevices
            .enumerateDevices()
            .then(function (dispositivos) {
                const dispositivosDeVideo = [];
                dispositivos.forEach(function (dispositivo) {
                    const tipo = dispositivo.kind;
                    if (tipo === "videoinput") {
                        dispositivosDeVideo.push(dispositivo);
                    }
                });

                // Vemos si encontramos algún dispositivo, y en caso de que si, entonces llamamos a la función
                if (dispositivosDeVideo.length > 0) {
                    // Llenar el select
                    dispositivosDeVideo.forEach(dispositivo => {
                        const option = document.createElement('option');
                        option.value = dispositivo.deviceId;
                        option.text = dispositivo.label;
                        $listaDeDispositivos.appendChild(option);
                        //console.log("$listaDeDispositivos => ", $listaDeDispositivos)
                    });
                }
            });
    }

    (function () {
        // Comenzamos viendo si tiene soporte, si no, nos detenemos
        if (!tieneSoporteUserMedia()) {
            alert("Lo siento. Tu navegador no soporta esta característica");
            $estado.innerHTML = "Parece que tu navegador no soporta esta característica. Intenta actualizarlo.";
            return;
        }
        //Aquí guardaremos el stream globalmente
        let stream;


        // Comenzamos pidiendo los dispositivos
        navigator
            .mediaDevices
            .enumerateDevices()
            .then(function (dispositivos) {
                // Vamos a filtrarlos y guardar aquí los de vídeo
                const dispositivosDeVideo = [];

                // Recorrer y filtrar
                dispositivos.forEach(function (dispositivo) {
                    const tipo = dispositivo.kind;
                    if (tipo === "videoinput") {
                        dispositivosDeVideo.push(dispositivo);
                    }
                });

                // Vemos si encontramos algún dispositivo, y en caso de que si, entonces llamamos a la función
                // y le pasamos el id de dispositivo
                if (dispositivosDeVideo.length > 0) {
                    // Mostrar stream con el ID del primer dispositivo, luego el usuario puede cambiar
                    mostrarStream(dispositivosDeVideo[0].deviceId);
                }
            });

        const mostrarStream = idDeDispositivo => {
            _getUserMedia(
                {
                    video: {
                        // Justo aquí indicamos cuál dispositivo usar
                        deviceId: idDeDispositivo,
                    }
                },
                function (streamObtenido) {
                    // Aquí ya tenemos permisos, ahora sí llenamos el select,
                    // pues si no, no nos daría el nombre de los dispositivos
                    llenarSelectConDispositivosDisponibles();

                    // Escuchar cuando seleccionen otra opción y entonces llamar a esta función
                    $listaDeDispositivos.onchange = () => {
                        // Detener el stream
                        if (stream) {
                            stream.getTracks().forEach(function (track) {
                                track.stop();
                            });
                        }
                        // Mostrar el nuevo stream con el dispositivo seleccionado
                        mostrarStream($listaDeDispositivos.value);
                    }

                    // Simple asignación
                    stream = streamObtenido;

                    // Mandamos el stream de la cámara al elemento de vídeo
                    $video.srcObject = stream;
                    $video.play();

                    //Escuchar el click del botón para tomar la foto
                    $boton.addEventListener("click", function () {
                        event.preventDefault();

                        //Pausar reproducción
                        $video.pause();

                        //Obtener contexto del canvas y dibujar sobre él
                        let contexto = $canvas.getContext("2d");
                        $canvas.width = $video.videoWidth;
                        $canvas.height = $video.videoHeight;
                        contexto.drawImage($video, 0, 0, $canvas.width, $canvas.height);

                        const foto = $canvas.toDataURL().split(',')[1];; //Esta es la foto, en base 64


                        $estado.innerHTML = "Enviando foto. Por favor, espera...";

                        /*var uri = '@Url.Action("Busqueda", "Vendedors")';
                        //enviar imagen al controlador
                        $.ajax({
                            url: uri,
                            type: 'POST',
                                        data: { imagen: foto }

                        });*/
                        document.querySelector('#imagen').value = foto;
                        form.submit();


                    });
                }, function (error) {
                    console.log("Permiso denegado o error: ", error);
                    $estado.innerHTML = "No se puede acceder a la cámara, o no diste permiso.";
                });
        }
    })();
</script>

Views/Vendedors/BusquedaSubir.cshtml
@{
    ViewBag.Title = "BusquedaSubir";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"]</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css">
    <style>
        .product-image {
            max-width: 100%;
            max-height: 100vh;
            width: auto;
            margin: 0 auto;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        /* Estilo para los botones fijos en la parte inferior */
        .fixed-buttons {
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            background-color: white;
            z-index: 1;
            padding: 10px;
            box-shadow: 0px -5px 10px rgba(0, 0, 0, 0.1);
            justify-content: center;
            align-items: center;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="row">
            <div >
                <!-- Formulario para cargar una imagen -->
                <form action="@Url.Action("BusquedaSubir", "Vendedors")" method="post" enctype="multipart/form-data">
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <label for="imagenFile">Selecciona una imagen:</label>
                        <input type="file" name="imagenFile" id="imagenFile" class="form-control-file" accept="image/*" required>
                    </div>

                    <!-- Vista previa de la imagen seleccionada -->
                    <div class="form-group" st>
                        <img id="imagenPreview" src="#" alt="Vista previa de la imagen" class="product-image">
                    </div>

                    <button type="submit" class="btn btn-primary fixed-buttons">Buscar</button>
                </form>

                <!-- Mostrar un mensaje si hay un ViewBag llamado "mje" -->
                @if (!string.IsNullOrEmpty(ViewBag.mje))
                {
                    <p>@ViewBag.mje</p>
                }
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Función para mostrar una vista previa de la imagen seleccionada
        $(document).ready(function () {
            $('#imagenFile').change(function () {
                previewImage(this);
            });

            function previewImage(input) {
                if (input.files && input.files[0]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $('#imagenPreview').attr('src', e.target.result);
                        $('#imagenPreview').show();
                    }

                    reader.readAsDataURL(input.files[0]);
                }
            }
        });
    </script>
</body>

</html>